In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

# import os
# print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['test.csv', 'train.csv', 'sample_submission.csv', 'data_description.txt']

## Importing libraries.

In [3]:
import pandas as pd
import numpy as np

In [4]:
data_train = pd.read_csv('../week4/Data-house/train.csv')
data_test = pd.read_csv('../week4/Data-house/test.csv')
data_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
y_train = data_train['SalePrice']
#price.head()
data_train.drop('SalePrice', axis=1, inplace = True)
data_train.head()
train_n = data_train.shape[0]
test_id = data_test['Id']

In [6]:
#data_test.head()
all_data = pd.concat((data_train,data_test))
all_data = all_data.reset_index(drop=True)
all_data.drop('Id', axis=True, inplace=True)
all_data.head()
#data_var = data.iloc[:,:-1]
#data_var.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

## HeatMap for corelation

In [8]:
#pd.get_dummies(data_var, columns=['MSZoning']).head()

## Filling out missing values in dataset

In [9]:
all_data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition'],
      dtype='object')

 ## Spread of missing value.

In [11]:
all_data['PoolQC'].fillna(value='None', inplace=True)

In [12]:
all_data['MiscFeature'].fillna(value='None', inplace=True)

In [13]:
all_data['Alley'].fillna(value='None', inplace=True)

In [14]:
all_data['Fence'].fillna(value='None', inplace=True)

In [15]:
all_data['FireplaceQu'].fillna(value='None', inplace=True)

In [16]:
median = all_data['LotFrontage'].median()
all_data['LotFrontage'].fillna(value=median, inplace=True)

In [17]:
for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    all_data[col] = all_data[col].fillna('None')

In [18]:
missing_vals[missing_vals>0]

PoolQC          2909
MiscFeature     2814
Alley           2721
Fence           2348
FireplaceQu     1420
LotFrontage      486
GarageCond       159
GarageQual       159
GarageYrBlt      159
GarageFinish     159
GarageType       157
BsmtCond          82
BsmtExposure      82
BsmtQual          81
BsmtFinType2      80
BsmtFinType1      79
MasVnrType        24
MasVnrArea        23
MSZoning           4
BsmtHalfBath       2
Utilities          2
Functional         2
BsmtFullBath       2
BsmtFinSF2         1
BsmtFinSF1         1
Exterior2nd        1
BsmtUnfSF          1
TotalBsmtSF        1
Exterior1st        1
SaleType           1
Electrical         1
KitchenQual        1
GarageArea         1
GarageCars         1
dtype: int64

In [19]:
for _ in ('GarageYrBlt', 'GarageArea', 'GarageCars'):
    all_data[_].fillna(value=0, inplace=True)

In [20]:
all_data[all_data['Utilities']!='AllPub']['Utilities']

944     NoSeWa
1915       NaN
1945       NaN
Name: Utilities, dtype: object

In [21]:
for _ in ['BsmtCond', 'BsmtExposure', 'BsmtQual', 'BsmtFinType2', 'BsmtFinType1']:
    all_data[_].fillna(value='None', inplace=True)

In [22]:
for _ in ['BsmtHalfBath', 'BsmtFullBath', 'BsmtFinSF2', 'BsmtFinSF1', 'BsmtUnfSF', 'TotalBsmtSF']:
    all_data[_].fillna(value=0, inplace=True)

In [23]:
all_data['MasVnrType'].fillna(value='None', inplace=True)

In [24]:
all_data['MasVnrArea'].fillna(value=0, inplace=True)

In [25]:
mode = all_data['MSZoning'].mode()[0]
all_data['MSZoning'].fillna(value=mode, inplace=True)

In [26]:
#as most all of the values are allpubs and in trainning set and test setexect one in trainnig set, we will frop this feature
all_data.drop(labels='Utilities', axis=1, inplace=True)

In [27]:
mode = all_data['Functional'].mode()[0]
all_data['Functional'].fillna(value=mode, inplace=True)
#all_data[all_data['Functional'].isnull()]

In [28]:
mode = all_data['Exterior2nd'].mode()[0]
all_data['Exterior2nd'].fillna(value=mode, inplace=True)

In [29]:
mode = all_data['Exterior1st'].mode()[0]
all_data['Exterior1st'].fillna(value=mode, inplace=True)

In [30]:
mode = all_data['SaleType'].mode()[0]
all_data['SaleType'].fillna(value=mode, inplace=True)

In [31]:
mode = all_data['Electrical'].mode()[0]
all_data['Electrical'].fillna(value=mode, inplace=True)

In [32]:
mode = all_data['KitchenQual'].mode()[0]
all_data['KitchenQual'].fillna(value=mode, inplace=True)

In [33]:
#NO more NaN values
xx=all_data.isnull().sum().sort_values(ascending=False)
xx[xx>0]
'OverallQual', 'OverallCond'

('OverallQual', 'OverallCond')

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
all_data_old = all_data

cols = ('FireplaceQu', 'BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond', 
        'ExterQual', 'ExterCond','HeatingQC', 'PoolQC', 'KitchenQual', 'BsmtFinType1', 
        'BsmtFinType2', 'Functional', 'Fence', 'BsmtExposure', 'GarageFinish', 'LandSlope',
       'LotShape', 'PavedDrive', 'Street', 'Alley', 'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold')
for c in cols:
    le.fit(all_data[c])
    r=le.transform(all_data[c])
    all_data[c]=r
all_data = pd.get_dummies(all_data)

In [35]:
## Seperating training and testing data
train_n
train_new = all_data[:train_n]
test_new = all_data[train_n:]

In [46]:
all_data.head(1469)

,MSSubClass,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,YearBuilt,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,5,65.0,8450,1,1,3,0,7,4,2003,...,0,0,0,1,0,0,0,0,1,0
1,0,80.0,9600,1,1,3,0,6,7,1976,...,0,0,0,1,0,0,0,0,1,0
2,5,68.0,11250,1,1,0,0,7,4,2001,...,0,0,0,1,0,0,0,0,1,0
3,6,60.0,9550,1,1,0,0,7,4,1915,...,0,0,0,1,1,0,0,0,0,0
4,5,84.0,14260,1,1,0,0,8,4,2000,...,0,0,0,1,0,0,0,0,1,0
5,4,85.0,14115,1,1,0,0,5,4,1993,...,0,0,0,1,0,0,0,0,1,0
6,0,75.0,10084,1,1,3,0,8,4,2004,...,0,0,0,1,0,0,0,0,1,0
7,5,68.0,10382,1,1,0,0,7,5,1973,...,0,0,0,1,0,0,0,0,1,0
8,4,51.0,6120,1,1,3,0,7,4,1931,...,0,0,0,1,1,0,0,0,0,0
9,15,50.0,7420,1,1,3,0,5,5,1939,...,0,0,0,1,0,0,0,0,1,0
10,0,70.0,11200,1,1,3,0,5,4,1965,...,0,0,0,1,0,0,0,0,1,0
11,5,85.0,11924,1,1,0,0,9,4,2005,...,0,1,0,0,0,0,0,0,0,1
12,0,68.0,12968,1,1,1,0,5,5,1962,...,0,0,0,1,0,0,0,0,1,0
13,0,91.0,10652,1,1,0,0,7,4,2006,...,0,1,0,0,0,0,0,0,0,1
14,0,68.0,10920,1,1,0,0,6,4,1960,...,0,0,0,1,0,0,0,0,1,0
15,3,51.0,6120,1,1,3,0,7,7,1929,...,0,0,0,1,0,0,0,0,1,0
16,0,68.0,11241,1,1,0,0,6,6,1970,...,0,0,0,1,0,0,0,0,1,0
17,10,72.0,10791,1,1,3,0,4,4,1967,...,0,0,0,1,0,0,0,0,1,0
18,0,66.0,13695,1,1,3,0,5,4,2004,...,0,0,0,1,0,0,0,0,1,0
19,0,70.0,7560,1,1,3,0,5,5,1958,...,0,0,0,0,1,0,0,0,0,0
20,5,101.0,14215,1,1,0,0,8,4,2005,...,0,1,0,0,0,0,0,0,0,1
21,3,57.0,7449,1,0,3,0,7,6,1930,...,0,0,0,1,0,0,0,0,1,0
22,0,75.0,9742,1,1,3,0,8,4,2002,...,0,0,0,1,0,0,0,0,1,0
23,11,44.0,4224,1,1,3,0,5,6,1976,...,0,0,0,1,0,0,0,0,1,0
24,0,68.0,8246,1,1,0,0,5,7,1968,...,0,0,0,1,0,0,0,0,1,0
25,0,110.0,14230,1,1,3,0,8,4,2007,...,0,0,0,1,0,0,0,0,1,0
26,0,60.0,7200,1,1,3,0,5,6,1951,...,0,0,0,1,0,0,0,0,1,0
27,0,98.0,11478,1,1,3,0,8,4,2007,...,0,0,0,1,0,0,0,0,1,0
28,0,47.0,16321,1,1,0,0,5,5,1957,...,0,0,0,1,0,0,0,0,1,0
29,1,60.0,6324,1,1,0,0,4,5,1927,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,5,80.0,11584,1,1,3,0,7,5,1979,...,0,0,0,1,0,0,0,0,1,0
1440,6,79.0,11526,1,1,0,1,6,6,1922,...,0,0,0,1,0,0,0,0,1,0
1441,11,68.0,4426,1,1,3,0,6,4,2004,...,0,0,0,1,0,0,0,0,1,0
1442,5,85.0,11003,1,1,3,0,10,4,2008,...,0,0,0,1,0,0,0,0,1,0
1443,1,68.0,8854,1,1,3,0,6,5,1916,...,0,0,0,1,0,0,0,0,1,0
1444,0,63.0,8500,1,1,3,0,7,4,2004,...,0,0,0,1,0,0,0,0,1,0
1445,9,70.0,8400,1,1,3,0,6,4,1966,...,0,0,0,1,0,0,0,0,1,0
1446,0,68.0,26142,1,1,0,0,5,6,1962,...,0,0,0,1,0,0,0,0,1,0
1447,5,80.0,10000,1,1,3,0,8,4,1995,...,0,0,0,1,0,0,0,0,1,0
1448,4,70.0,11767,1,1,3,0,4,6,1910,...,0,0,0,1,0,0,0,0,1,0
1449,14,21.0,1533,1,1,3,0,5,6,1970,...,0,0,0,1,1,0,0,0,0,0
1450,10,60.0,9000,1,1,3,0,5,4,1974,...,0,0,0,1,0,0,0,0,1,0
1451,0,78.0,9262,1,1,3,0,8,4,2008,...,0,1,0,0,0,0,0,0,0,1
1452,14,35.0,3675,1,1,3,0,5,4,2005,...,0,0,0,1,0,0,0,0,1,0
1453,0,90.0,17217,1,1,3,0,5,4,2006,...,0,0,0,1,1,0,0,0,0,0
1454,0,62.0,7500,1,2,3,0,7,4,2004,...,0,0,0,1,0,0,0,0,1,0
1455,5,62.0,7917,1,1,3,0,6,4,1999,...,0,0,0,1,0,0,0,0,1,0
1456,0,85.0,13175,1,1,3,0,6,5,1978,...,0,0,0,1,0,0,0,0,1,0
1457,6,66.0,9042,1,1,3,0,7,8,1941,...,0,0,0,1,0,0,0,0,1,0
1458,0,68.0,9717,1,1,3,0,5,5,1950,...,0,0,0,1,0,0,0,0,1,0
1459,0,75.0,9937,1,1,3,0,5,5,1965,...,0,0,0,1,0,0,0,0,1,0
1460,0,80.0,11622,1,1,3,0,5,5,1961,...,0,0,0,1,0,0,0,0,1,0
1461,0,81.0,14267,1,1,0,0,6,5,1958,...,0,0,0,1,0,0,0,0,1,0
1462,5,74.0,13830,1,1,0,0,5,4,1997,...,0,0,0,1,0,0,0,0,1,0
1463,5,78.0,9978,1,1,0,0,6,5,1998,...,0,0,0,1,0,0,0,0,1,0
1464,11,43.0,5005,1,1,0,0,8,4,1992,...,0,0,0,1,0,0,0,0,1,0
1465,5,75.0,10000,1,1,0,0,6,4,1993,...,0,0,0,1,0,0,0,0,1,0
1466,0,68.0,7980,1,1,0,0,6,6,1992,...,0,0,0,1,0,0,0,0,1,0
1467,5,63.0,8402,1,1,0,0,6,4,1998,...,0,0,0,1,0,0,0,0,1,0
1468,0,85.0,10176,1,1,3,0,7,4,1990,...,0,0,0,1,0,0,0,0,1,0

In [35]:
## Appling Decision tree and linear regressor for prediction.
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(min_samples_split=10)
dtr.fit(train_new, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=10, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [36]:
dtr.score(train_new, y_train)
from sklearn.linear_model import Ridge
lr = Ridge()
lr.fit(train_new, y_train)
lr.score(train_new, y_train)

0.9090481032834945

In [37]:
sub = lr.predict(test_new)
sub

array([108506.09260242, 150796.39418559, 169824.23543665, ...,
       157694.68268972, 101165.04297317, 228995.94027604])

In [38]:
df = pd.DataFrame()
df['Id']=test_id
df['SalePrice']=sub
df.to_csv('submission.csv',index=False)